-- Seed completo de catálogo FACIAL/CORPORAL desde JSON locales.
-- Fuente: servicios_facial.json (59) + servicios_corporal.json (36)
-- Dedupe por (lower(trim(nombre)), cat); no pisa precios de registros ya existentes.

insert into public.servicios (nombre, cat, duracion, precio, sesiones, descripcion)
select *
from (
  values
    ('NEUROMODULADOR (AZZALURE)','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('1 VIAL ACIDO HIALURONICO','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('1/2 VIAL ACIDO HIALURONICO','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('RADIESSE (HIDROXIAPATITA DE CALCIO)','facial',45,350.00,1,'Importado desde catálogo externo'),
    ('HILOS ESPICULADOS (4 HILOS)','facial',45,350.00,1,'Importado desde catálogo externo'),
    ('LIMP FACIAL + DERMOABRASION + ESPATULA ULTRASONICA','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('RADIOFREC ROSTRO','facial',45,280.00,1,'Importado desde catálogo externo'),
    ('LASER CO2 + RESURFACING','facial',45,250.00,1,'Importado desde catálogo externo'),
    ('LIMPIEZA FACIAL / VIT DERMAPEN / PEELING / DERMAPLANNING','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('OFERTA LIMPIEZA FACIAL + PEELING/VITAMINAS','facial',45,90.00,1,'Importado desde catálogo externo'),
    ('ASTAXANTINA + TONICO','facial',45,160.00,1,'Importado desde catálogo externo'),
    ('CORTICOIDE / MESOTERAPIA','facial',45,50.00,1,'Importado desde catálogo externo'),
    ('BBLIPS / BB GLOW (PORCELANIZACION)','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('EXOSOMAS FACIAL','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('DENEB 1 VIAL','facial',45,400.00,1,'Importado desde catálogo externo'),
    ('HILOS LIQUIDOS','facial',45,10.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION ENZIMAS','facial',45,50.00,1,'Importado desde catálogo externo'),
    ('TTO 1 LOBULO','facial',45,400.00,1,'Importado desde catálogo externo'),
    ('COSMELAN','facial',45,550.00,1,'Importado desde catálogo externo'),
    ('MOLDEO FACIAL','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('HIFU FACIAL + CUELLO','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('K-LASER ROSACEA','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('K-LASER RESURFACING','facial',45,100.00,1,'Importado desde catálogo externo'),
    ('K-LASER MANEJO DEL DOLOR','facial',45,40.00,1,'Importado desde catálogo externo'),
    ('LASER TATOO PEQUEÑO O CEJAS','facial',45,50.00,1,'Importado desde catálogo externo'),
    ('LASER TATOO MEDIANO','facial',45,80.00,1,'Importado desde catálogo externo'),
    ('ASTAXANTINA','facial',45,100.00,1,'Importado desde catálogo externo'),
    ('KOBIDO','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('PLASMAPEN 1 ZONA','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('HOLLYWOOD PEEL','facial',45,70.00,1,'Importado desde catálogo externo'),
    ('ROSE DE MER FACIAL','facial',45,220.00,1,'Importado desde catálogo externo'),
    ('SEVENTY HYAL','facial',45,200.00,1,'Importado desde catálogo externo'),
    ('K-LASER VERRUGAS DE 1-5','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('K-LASER VERRUGAS 5-10','facial',45,100.00,1,'Importado desde catálogo externo'),
    ('HIDRATACION PROFUNDA','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('K-LASER VASCULAR FACIAL','facial',45,60.00,1,'Importado desde catálogo externo'),
    ('K-LASER MANCHAS MODERADAS','facial',45,80.00,1,'Importado desde catálogo externo'),
    ('HIFU NARIZ','facial',45,270.00,1,'Importado desde catálogo externo'),
    ('K-LASER ACNE LEVE','facial',45,80.00,1,'Importado desde catálogo externo'),
    ('K-LASER ACNE SEVERO','facial',45,110.00,1,'Importado desde catálogo externo'),
    ('TTO OJERAS NCTF','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('LASER','facial',45,200.00,1,'Importado desde catálogo externo'),
    ('HIFU','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('ARMONIZACION Y NARIZ CON HIFU','facial',45,300.00,1,'Importado desde catálogo externo'),
    ('1 VIAL DE A.H. (SEGUNDO)','facial',45,230.00,1,'Importado desde catálogo externo'),
    ('CO2 FACIAL','facial',45,230.00,1,'Importado desde catálogo externo'),
    ('VIT FACIALES COMPLETAS / PDR','facial',45,0.00,1,'Importado desde catálogo externo'),
    ('HILOS PDO','facial',45,10.00,1,'Importado desde catálogo externo'),
    ('SCULPTRA','facial',45,500.00,1,'Importado desde catálogo externo'),
    ('INDIBA FACIAL (ROSTRO+CUELLO+ESCOTE)','facial',45,70.00,1,'Importado desde catálogo externo'),
    ('HILOS LIQUIDOS O NANO BOTOX CON DERMAPEN','facial',45,80.00,1,'Importado desde catálogo externo'),
    ('TTO OJERAS EYECON','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('LIPOLASER / ALECTOMIA','facial',45,1300.00,1,'Importado desde catálogo externo'),
    ('MESOTERAPIA FACIAL','facial',45,150.00,1,'Importado desde catálogo externo'),
    ('RADIOFREC FACIAL+CUELLO+ROSTRO','facial',45,430.00,1,'Importado desde catálogo externo'),
    ('OJERAS / SESION CORRIENTE GALVANICA','facial',45,30.00,1,'Importado desde catálogo externo'),
    ('POLINUCLEOTIDOS','facial',45,220.00,1,'Importado desde catálogo externo'),
    ('CO2 ZONA PEQUEÑA','facial',45,100.00,1,'Importado desde catálogo externo'),
    ('POST PAPADA','facial',45,50.00,1,'Importado desde catálogo externo'),
    ('MASAJE REDUCTOR / DRENANTE','corporal',45,60.00,1,'Importado desde catálogo externo'),
    ('MASAJE POSQURURJICO','corporal',45,90.00,1,'Importado desde catálogo externo'),
    ('CORPOSHAPE','corporal',45,70.00,1,'Importado desde catálogo externo'),
    ('LIPOLED','corporal',45,60.00,1,'Importado desde catálogo externo'),
    ('PRESOTERAPIA / CAMILLA ANDULACION','corporal',45,20.00,1,'Importado desde catálogo externo'),
    ('EMSCULPT','corporal',45,40.00,1,'Importado desde catálogo externo'),
    ('RADIOFRECUENCIA ZONA PEQUEÑA','corporal',45,50.00,1,'Importado desde catálogo externo'),
    ('RADIOFR. ABDOMEN','corporal',45,400.00,1,'Importado desde catálogo externo'),
    ('ROSE DE MER GLUTEO O ESPALDA','corporal',45,350.00,1,'Importado desde catálogo externo'),
    ('ESCLEROTERAPIA (1 AMPOLLA)','corporal',45,90.00,1,'Importado desde catálogo externo'),
    ('ESCLEROTERAPIA (2 AMPOLLAS)','corporal',45,140.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION VIT C/ TTO GRASA','corporal',45,50.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION MULTIVITAMINICO','corporal',45,70.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION PEPTONA / GLUTEOX / FITOX','corporal',45,100.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION ENZIMAS','corporal',45,150.00,1,'Importado desde catálogo externo'),
    ('MASOTERAPIA','corporal',45,90.00,1,'Importado desde catálogo externo'),
    ('METALTERAPIA / MASAJE TERAPEUTICO','corporal',45,70.00,1,'Importado desde catálogo externo'),
    ('LASER CO2 ZONA PEQUEÑA','corporal',45,50.00,1,'Importado desde catálogo externo'),
    ('HIDROMASAJE','corporal',45,120.00,1,'Importado desde catálogo externo'),
    ('DESPIGMENTACION 1 ZONA','corporal',45,60.00,1,'Importado desde catálogo externo'),
    ('MARC ABD CON ELETROPORACION + HIFU','corporal',45,350.00,1,'Importado desde catálogo externo'),
    ('K-LASER PIERNAS (VASCULAR)','corporal',45,160.00,1,'Importado desde catálogo externo'),
    ('DERMAMELAN','corporal',45,100.00,1,'Importado desde catálogo externo'),
    ('LASER CO2 ZONA MEDIANA','corporal',45,100.00,1,'Importado desde catálogo externo'),
    ('ELECTROPORACION ALCACHOFA O 1 AMPOLLA','corporal',45,20.00,1,'Importado desde catálogo externo'),
    ('CARBON SESION','corporal',45,45.00,1,'Importado desde catálogo externo'),
    ('INDIBA ABDOMEN / ANTICELULITICO','corporal',45,70.00,1,'Importado desde catálogo externo'),
    ('LASER CO2 ZONA GRANDE','corporal',45,200.00,1,'Importado desde catálogo externo'),
    ('TRATAMIENTO DE MANOS','corporal',45,200.00,1,'Importado desde catálogo externo'),
    ('EXFOLIACION CORPORAL','corporal',45,160.00,1,'Importado desde catálogo externo'),
    ('ONDAS DE CHOQUE','corporal',45,70.00,1,'Importado desde catálogo externo'),
    ('SILLA EMS','corporal',45,60.00,1,'Importado desde catálogo externo'),
    ('SESION MANTA','corporal',45,45.00,1,'Importado desde catálogo externo'),
    ('CARBO EN OJERAS','corporal',45,30.00,1,'Importado desde catálogo externo'),
    ('SERVICIO CORPORAL 029 (SIN DESCRIPCION)','corporal',45,0.00,1,'Importado desde catálogo externo'),
    ('SESION QUIROPRACTICO','corporal',45,150.00,1,'Importado desde catálogo externo')
) as v(nombre, cat, duracion, precio, sesiones, descripcion)
where not exists (
  select 1
  from public.servicios s
  where lower(trim(s.nombre)) = lower(trim(v.nombre))
    and s.cat = v.cat
);
