-- Seed catálogo de servicios de la clínica GOYA (FLOWWW 813060).
-- Fuente: "LISTA PRECIOS Y SERVICIOS GOYA" (Excel del cliente, 88 servicios).
-- Bloques: Medicina estética, Estética avanzada, Aparatología médica/estética,
-- Depilación láser diodo, Láser médico y Tratamientos especiales.
-- Idempotente: deduplica por (lower(trim(nombre)), cat) y NO pisa precios ya existentes.

insert into public.servicios (nombre, cat, duracion, precio, sesiones, descripcion)
select *
from (
  values
    ('AH Pómulo (1 vial )','facial',60,270.00,1,'GOYA · Medicina estética · Facial'),
    ('Baby Botox','facial',60,150.00,1,'GOYA · Medicina estética · Facial'),
    ('Botox 1 (1 vial )','facial',60,270.00,1,'GOYA · Medicina estética · Facial · 1 vial · Marca/Nota: CROMA'),
    ('Botox 2 (1 vial)','facial',60,300.00,1,'GOYA · Medicina estética · Facial · 1 vial · Marca/Nota: AXALURE'),
    ('Botox Bruxismo','facial',30,270.00,1,'GOYA · Medicina estética · Facial'),
    ('Botox Hiperhidrosis','facial',30,270.00,1,'GOYA · Medicina estética · Facial · 2 VIALES ***'),
    ('Diseño de labios (1 vial)','facial',60,270.00,1,'GOYA · Medicina estética · Facial · 1 vial'),
    ('Diseño de labios (1/2 vial)','facial',90,150.00,1,'GOYA · Medicina estética · Facial · 1/2 vial'),
    ('Enzimas facial','facial',60,50.00,1,'GOYA · Medicina estética · Facial'),
    ('EXOSOMAS','facial',90,200.00,1,'GOYA · Medicina estética · Facial · inyectado más dermapen'),
    ('Foxy Eyes (4 hilos y punto de botox)','facial',60,350.00,1,'GOYA · Medicina estética · Facial · 4 hilos y punto de botox'),
    ('Hilos tensores espiculados (4 hilos)','facial',45,350.00,1,'GOYA · Medicina estética · Facial · 4 hilos'),
    ('Marcación mandibular (1 vial)','facial',45,320.00,1,'GOYA · Medicina estética · Facial · 1 vial · Hablar con David precio por vial o por tto?? pudiese ser mrc mnd hombre y marc man chica'),
    ('NCTF inyectado','facial',45,200.00,1,'GOYA · Medicina estética · Facial · inyectado'),
    ('NCTF dermapen','facial',45,150.00,1,'GOYA · Medicina estética · Facial · dermapen'),
    ('Polinucleótidos salmón (Mesoterapia más dermapen)','facial',45,220.00,1,'GOYA · Medicina estética · Facial · Mesoterapia más dermapen'),
    ('Radiesse (1 vial )','facial',45,350.00,1,'GOYA · Medicina estética · Facial · 1 vial'),
    ('Rinomodelación (1 vial )','facial',45,300.00,1,'GOYA · Medicina estética · Facial · 1 vial'),
    ('Sculptra (1 vial )','facial',45,500.00,1,'GOYA · Medicina estética · Facial · 1 vial'),
    ('Escleoterapia (1 vial )','facial',45,90.00,1,'GOYA · Medicina estética · Facial · 1 Vial'),
    ('Escleoterapia (2 vial )','corporal',45,150.00,1,'GOYA · Medicina estética · Corporal · 2 Viales'),
    ('VACUNA OBESIDAD','corporal',45,80.00,1,'GOYA · Medicina estética · Corporal · 1 Vial'),
    ('HIDROLIPOCLASIA (+5s corposhape + preso)','corporal',45,450.00,1,'GOYA · Medicina estética · Corporal'),
    ('HIALURONIDASA','corporal',45,50.00,1,'GOYA · Medicina estética · Corporal · 1VIAL'),
    ('Peeling Fenol','corporal',45,0.00,1,'GOYA · Medicina estética · Corporal · Marca/Nota: preg david · Precio a confirmar (preg david)'),
    ('ASTAXANTINA','facial',45,160.00,1,'GOYA · Estética avanzada · Facial · Dermapen · Incluye kit para casa'),
    ('COSMELAN','facial',45,550.00,1,'GOYA · Estética avanzada · Facial · Incluye kit de casa, dos revisiones inlcu mitad tto y final tto para hacerte hdrtacion prodf Duración: mes ymedio pero ANTES debe tomar depurpati (quita manchas de adentro a fuera) no tomar picante'),
    ('Higiene','facial',45,79.00,1,'GOYA · Estética avanzada · Facial'),
    ('Higiene premium (Hidrafacial)','facial',45,120.00,1,'GOYA · Estética avanzada · Facial'),
    ('VITAMINAS','facial',45,60.00,1,'GOYA · Estética avanzada · Facial · DERMAPEN'),
    ('Higiene más Vitaminas','facial',45,99.00,1,'GOYA · Estética avanzada · Facial · Dermapen · Marca/Nota: promo'),
    ('Peeling con Acido Salisilico','facial',45,50.00,1,'GOYA · Estética avanzada · Facial'),
    ('Plasmapen ojeras','facial',45,100.00,1,'GOYA · Estética avanzada · Facial'),
    ('Plasmapen cuello más pómulo','facial',45,250.00,1,'GOYA · Estética avanzada · Facial'),
    ('MADEROTERAPIA/METALTERAPIA','corporal',45,50.00,1,'GOYA · Estética avanzada · Corporal'),
    ('CAVITACIÓN MAS MADERO','corporal',45,60.00,1,'GOYA · Estética avanzada · Corporal'),
    ('MASOTERAPIA','corporal',45,90.00,1,'GOYA · Estética avanzada · Corporal'),
    ('HIFU — Pómulo más cuello','facial',45,150.00,1,'GOYA · Aparatología médica · Facial'),
    ('HIFU — Cara completa más cuello','facial',45,200.00,1,'GOYA · Aparatología médica · Facial'),
    ('HIFU — Nariz','facial',45,50.00,1,'GOYA · Aparatología médica · Facial'),
    ('Radio frecuencia CC — Cara completa - cuello','facial',45,430.00,1,'GOYA · Aparatología médica · Facial · Incluye kit'),
    ('Personalizado facial','facial',45,100.00,1,'GOYA · Aparatología médica · Facial · Bono 5: 450€'),
    ('ONDAS DE CHOQUE — PIERNAS','facial',45,70.00,1,'GOYA · Aparatología médica · Facial · Bono 5: 300€'),
    ('Radio frecuencia TI — CaraTercio inferior','facial',45,280.00,1,'GOYA · Aparatología médica · Facial · Incluye kit para tres días'),
    ('HIFU — Abdomen Y Piernas','facial',45,400.00,1,'GOYA · Aparatología médica · Facial'),
    ('EMS — Sesión','corporal',45,50.00,1,'GOYA · Aparatología médica · Corporal · Bono 5: 230€ · Bono 10: 470€'),
    ('Carboxiterapia — Sesión','corporal',45,50.00,1,'GOYA · Aparatología médica · Corporal · Bono 5: 230€ · Bono 10: 470€'),
    ('Corposhape — Sesión','corporal',45,80.00,1,'GOYA · Aparatología médica · Corporal · Bono 5: 350€ · Bono 10: 770€'),
    ('Mesoterapia — Sesión','corporal',45,50.00,1,'GOYA · Aparatología médica · Corporal · Bono 5: 230€ · Bono 10: 470€'),
    ('Cavitación — Sesión','corporal',45,50.00,1,'GOYA · Aparatología estética'),
    ('Preso — Sesión','corporal',45,30.00,1,'GOYA · Aparatología estética · Bono 5: 130€ · Bono 10: 240€'),
    ('Radiofrecuencia abdomen — Sesión','corporal',45,400.00,1,'GOYA · Aparatología estética'),
    ('Radiofrecuencia Piernas — Sesión','corporal',45,400.00,1,'GOYA · Aparatología estética · Marca/Nota: 550 · Rango precio: 400 / 550€'),
    ('Radiofrecuencia brazos — Sesión','corporal',45,200.00,1,'GOYA · Aparatología estética'),
    ('Radiofrecuencia indiba 1 hora — Sesión','facial',45,50.00,1,'GOYA · Aparatología estética · Bono 5: 230€ · Bono 10: 470€'),
    ('Lipomarcación (Meso + HIFU) — Sesión','corporal',45,450.00,1,'GOYA · Aparatología estética'),
    ('Barbilla','facial',45,35.00,1,'GOYA · Depilación láser diodo · Facial · Bono 5: 155€ · Bono 10: 310€'),
    ('Facial completo','facial',45,60.00,1,'GOYA · Depilación láser diodo · Facial · Bono 5: 250€ · Bono 10: 460€'),
    ('Abdomen','corporal',45,40.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 180€ · Bono 10: 360€'),
    ('Axilas','corporal',45,45.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 205€ · Bono 10: 410€'),
    ('Bikini (pubis, labios, ingles y perianal)','corporal',45,60.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 280€ · Bono 10: 520€'),
    ('Brazos','corporal',45,45.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 205€ · Bono 10: 410€'),
    ('Espalda','corporal',45,55.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 255€ · Bono 10: 510€'),
    ('Gluteo','corporal',45,45.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 205€ · Bono 10: 410€'),
    ('Medias piernas','corporal',45,55.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 255€ · Bono 10: 510€'),
    ('Pecho','corporal',45,40.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 180€ · Bono 10: 360€'),
    ('Perianal','corporal',45,40.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 180€ · Bono 10: 360€'),
    ('Piernas completas','corporal',45,60.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 280€ · Bono 10: 520€'),
    ('Pubis','corporal',45,35.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 155€ · Bono 10: 310€'),
    ('Nuca','corporal',45,30.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 130€ · Bono 10: 260€'),
    ('Ingles','corporal',45,45.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 205€ · Bono 10: 410€'),
    ('CUERPO COMPLETO CHICA','corporal',45,240.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 1200€ · Bono 10: 2400€'),
    ('CUERPO COMPLETO CHICO','corporal',45,330.00,1,'GOYA · Depilación láser diodo · Corporal · Bono 5: 1650€ · Bono 10: 3300€'),
    ('LASER CO2','facial',45,200.00,1,'GOYA · Láser médico · Medico'),
    ('LASER CO2 CON RESURFACING','facial',45,300.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER ACNE VULGAR','facial',45,60.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER RESURFACING','facial',45,100.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER VASCULAR FACIAL','facial',45,60.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER VERRUGAS DE 1 - 5','facial',45,60.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER VERRUGAS DE 5 - 1O','facial',45,100.00,1,'GOYA · Láser médico · Medico'),
    ('K LASER MANCHAS MODERADAS','facial',45,80.00,1,'GOYA · Láser médico · Estetica'),
    ('K LASER MANEJO DEL DOLOR','facial',45,40.00,1,'GOYA · Láser médico · Estetica'),
    ('Q SWITCH LASER TATOO PEQUEÑO O CEJAS','facial',45,50.00,1,'GOYA · Láser médico · Estetica · HOLLIWOOD Y Eliminación de tatuajes y micropigmentación'),
    ('Q SWITCH LASER TATOO MEDIANO','facial',45,80.00,1,'GOYA · Láser médico · Estetica'),
    ('Q SWITCH LASER TATOO GRANDE','facial',45,80.00,1,'GOYA · Láser médico · Estetica'),
    ('Pers.facial 5ss ( Hig, Vit, Rf I, Vit y Rf I)','facial',45,240.00,5,'GOYA · Tratamientos especiales'),
    ('Pers. Corporal 5ss ( Vacum+masaje+copa vikinga+Pep + Vit C+EMS)','corporal',45,470.00,5,'GOYA · Tratamientos especiales'),
    ('Perso corporal (5ss indiba + 5 carbo)','corporal',45,500.00,5,'GOYA · Tratamientos especiales')
) as v(nombre, cat, duracion, precio, sesiones, descripcion)
where not exists (
  select 1
  from public.servicios s
  where lower(trim(s.nombre)) = lower(trim(v.nombre))
    and s.cat = v.cat
);
